---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cilium/ks.yaml
  - ./coredns/ks.yaml
  - ./csi-driver-nfs/ks.yaml
  - ./descheduler/ks.yaml
  - ./external-secrets/ks.yaml
  - ./local-path-provisioner/ks.yaml
  - ./metrics-server/ks.yaml
  - ./namespace.yaml
  - ./nvidia-gpu-operator/ks.yaml
  - ./reloader/ks.yaml
  - ./snapshot-controller/ks.yaml
  #- ./vpa/ks.yaml
