---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  # - ./atuin/ks.yaml
  - ./authentik/ks.yaml
  - ./hoarder/ks.yaml
  - ./home-assistant/ks.yaml
  - ./immich/ks.yaml
  - ./it-tools/ks.yaml
  - ./memos/ks.yaml
  - ./miniflux/ks.yaml
  - ./paperless/ks.yaml
  - ./vikunja/ks.yaml
