---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/objectbucket.io/objectbucketclaim_v1alpha1.json
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: loki-bucket-v1
spec:
  bucketName: loki-v1
  storageClassName: ceph-bucket
