---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./atuin/ks.yaml
  - ./descheduler/ks.yaml
  - ./fstrim/ks.yaml
  - ./intel-device-plugin/ks.yaml
  - ./node-feature-discovery/ks.yaml
  - ./reloader/ks.yaml
  - ./snapshot-controller/ks.yaml
  - ./volsync/ks.yaml

