---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./cilium-l2.yaml
  - ./cilium-l3.yaml
  - ./cilium-pool.yaml
  - ./helmrelease.yaml
