---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./excalidraw/ks.yaml
  - ./hajimari/ks.yaml
  # - ./home-assistant/ks.yaml
  # - ./immich/ks.yaml
  - ./namespace.yaml
