---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coder
  namespace: dev
spec:
  interval: 30m
  chart:
    spec:
      chart: coder
      version: 2.1.4
      sourceRef:
        kind: HelmRepository
        name: coder
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # initContainers:
    #   01-init-db:
    #     image: ghcr.io/onedr0p/postgres-init:14.8
    #     imagePullPolicy: IfNotPresent
    #     envFrom:
    #       - secretRef:
    #           name: coder-secret
    coder:
      env:
      # DB
      - name: CODER_PG_CONNECTION_URL
        valueFrom:
          secretKeyRef:
            name: coder-secret
            key: CODER_PG_CONNECTION_URL
      # App
      - name: CODER_ACCESS_URL
        value: https://coder.${SECRET_DOMAIN}
      # Github
      - name: CODER_GITAUTH_0_ID
        valueFrom:
          secretKeyRef:
            name: coder-secret
            key: CODER_GITAUTH_0_ID
      - name: CODER_GITAUTH_0_TYPE
        valueFrom:
          secretKeyRef:
            name: coder-secret
            key: CODER_GITAUTH_0_TYPE
      - name: CODER_GITAUTH_0_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: coder-secret
            key: CODER_GITAUTH_0_CLIENT_ID
      - name: CODER_GITAUTH_0_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: coder-secret
            key: CODER_GITAUTH_0_CLIENT_SECRET
      # OIDC
      - name: CODER_OIDC_ISSUER_URL
        valueFrom:
          secretKeyRef:
            name: coder-secret
            key: CODER_OIDC_ISSUER_URL
      - name: CODER_OIDC_EMAIL_DOMAIN
        valueFrom:
          secretKeyRef:
            name: coder-secret
            key: CODER_OIDC_EMAIL_DOMAIN
      - name: CODER_OIDC_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: coder-secret
            key: CODER_OIDC_CLIENT_ID
      - name: CODER_OIDC_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: coder-secret
            key: CODER_OIDC_CLIENT_SECRET
      ingress:
        enable: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        host: "coder.${SECRET_DOMAIN}"
