---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: dcgm-exporter
  namespace: flux-system
spec:
  interval: 1h
  url: https://nvidia.github.io/dcgm-exporter/helm-charts
