---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: readmeabook
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: readmeabook-secret
    template:
      data:
        # App
        POSTGRES_DB: &dbName readmeabook
        DB_HOSTNAME: &dbHost postgres-rw.database.svc.cluster.local
        DB_PORT: "5432"
        POSTGRES_USER: &dbUser "{{ .POSTGRES_USER }}"
        POSTGRES_PASSWORD: &dbPass "{{ .POSTGRES_PASSWORD }}"
        DATABASE_URL: "postgresql://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASSWORD }}@postgres-rw.database.svc.cluster.local:5432/readmeabook"
        JWT_SECRET: "{{ .JWT_SECRET }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: readmeabook
    - extract:
        key: cloudnative-pg
