---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: loki-secret
    template:
      engineVersion: v2
      data:
        S3_BUCKET_NAME: "{{ .S3_BUCKET_NAME }}"
        S3_BUCKET_HOST: "{{ .MINIO_S3_URL }}"
        S3_BUCKET_REGION: "{{ .S3_BUCKET_REGION }}"
        S3_ACCESS_KEY: "{{ .S3_ACCESS_KEY }}"
        S3_SECRET_KEY: "{{ .S3_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: loki
    - extract:
        key: minio
