---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name minio
spec:
  staticConfigs:
    - targets:
        - s3.rodent.cc:9002
  metricsPath: /minio/v2/metrics/cluster
