---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system-upgrade
resources:
  - ./system-upgrade-controller/ks.yaml
components:
  - ../../flux/components/alerts
  - ../../flux/components/sops
  - ../../flux/components/namespace
patches:
  - # Add the name to the namespace
    patch: |
      - op: add
        path: /metadata/name
        value: system-upgrade
    target:
      kind: Namespace
