---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-nfs
spec:
  storageClassName: apps-nfs
  capacity:
    storage: 1Mi # Size does not matter
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${TRUENAS_IP}
    path: /mnt/cauldron/Apps/Immich
  # Note: The first two options are strictly for NFSv4.2
  mountOptions: ["nfsvers=4.2", "nconnect=8", "hard", "noatime"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-nfs
  namespace: default
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: immich-nfs
  resources:
    requests:
      storage: 1Mi # Size does not matter
