---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: actions-runner-controller-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: actions-runner-controller-auth-secret
    template:
      engineVersion: v2
      data:
        ACTION_RUNNER_CONTROLLER_GITHUB_APP_ID: |-
          {{ .ACTION_RUNNER_CONTROLLER_GITHUB_APP_ID }}
        ACTION_RUNNER_CONTROLLER_GITHUB_INSTALLATION_ID: |-
          {{ .ACTION_RUNNER_CONTROLLER_GITHUB_INSTALLATION_ID }}
        ACTION_RUNNER_CONTROLLER_GITHUB_PRIVATE_KEY: |-
          {{ .ACTION_RUNNER_CONTROLLER_GITHUB_PRIVATE_KEY }}
  dataFrom:
    - extract:
        key: actions-runner-controller
